# permissions for end users to edit healths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: health-editor-role
rules:
- apiGroups:
  - common.amadev.ru
  resources:
  - healths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - common.amadev.ru
  resources:
  - healths/status
  verbs:
  - get
